### ISSUE TITLE
Django outdated dependecy

### ISSUE THREAD

**Issue by danielboros1990** [jinkanhq/django-rest-tsg#1]
Is it possible to use this package with django@4+? It seems that doesn't work with v4.0.4.

**Comment by yinian1992** [comment]
Yes, it requires some testing for django 4.x, but it will be done soon.
Thank you for your attention.

**Comment by yinian1992** [comment]
Please use the newly released v0.1.7, it pass compatibility testing with Django 4.1 and DRF 3.14.
