### ISSUE TITLE
Optional field generation

### ISSUE THREAD

**Issue by biolds** [jinkanhq/django-rest-tsg#3]
Hello,

It seems optional field are not generated correctly. I have defined as:

```python
class MyModel(models.Model):
    description = models.TextField(null=True, blank=True)

class MySerializer(serializers.ModelSerializer):
    class Meta:
        model = MyModel
        fields = ('description',)
```

The generated Typescript file is:

```typescript
export interface MyModel {
  description: string?;
}
```

Which is rejected by Typescript, I think it should instead return:

```typescript
export interface MyModel {
  description: string | null;
}
```

Thanks for this great project!

**Comment by yuqiao20** [comment]
Thank you for your attention.
The bug has been confirmed. We'll fix it soon.
